name: time_slider
description: package to get a vertical slider of an time picker (or any type of text) where you can only choose one and set properties of selected and non selected items
version: 0.1.0
homepage:      https://github.com/guglia001/Time-picker-slider
repository:    https://github.com/guglia001/Time-picker-slider
issue_tracker: https://github.com/guglia001/Time-picker-slider/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
